from src.outreach.bundles import create_bundle
from src.schemas.inference import (
    GenerationSettings,
    InferenceRequest,
    InferenceResponse,
    InferenceResultBundle,
    ModelIdentity,
    OutreachOutput,
    RuntimeMetadata,
)


class DeterministicInferenceDouble:
    def __init__(self, model: ModelIdentity) -> None:
        self._model = model

    def generate(self, request: InferenceRequest) -> InferenceResultBundle:
        response = InferenceResponse(
            request_id=request.request_id,
            model=self._model,
            generation=GenerationSettings(
                max_new_tokens=request.max_new_tokens,
                seed=request.seed,
            ),
            output=OutreachOutput(
                subject="A relevant operational question",
                body=(
                    "This deterministic test output exercises the inference "
                    "contract without claiming that a live model was called."
                ),
                claims_used=request.approved_claim_ids,
                uncertainty_notes=["Generated by the local test double."],
            ),
            runtime=RuntimeMetadata(
                python_version="test",
                torch_version="not-loaded",
                transformers_version="not-loaded",
                cuda_version=None,
                gpu_name="deterministic-test-double",
                gpu_memory_mb=1,
                latency_ms=0.0,
            ),
        )
        return create_bundle(response)
